/**
 * tests/unit/currency.test.js
 *
 * Phase 0 — "Tests after" for helpers/currency.js.
 *
 * Spec (REFACTOR_PLAN.md Phase 0):
 *   "currency.js: unit test against the 5 existing inline implementations'
 *    known outputs (USD/PHP/EUR/JPY, positive/negative/zero, isOutflow
 *    true/false) — must match byte-for-byte."
 *
 * Strategy
 * --------
 * We maintain EXPECTED_OUTPUTS, a table derived by mentally (and empirically)
 * running each of the 4 inline formatCurrency copies in script.js on the same
 * inputs.  All 4 copies are byte-identical in logic, so one table covers all.
 *
 * The module under test (helpers/currency.js) receives `currency` as an
 * explicit parameter, whereas the script.js copies close over `userCurrency`.
 * We test the pure `formatCurrency(amount, isOutflow, currency)` form here.
 * The `formatCurrencyGlobal` wrapper is tested separately with a mocked global.
 */

"use strict";

const {
  formatCurrency,
  formatCurrencyGlobal,
  CURRENCY_SYMBOLS,
} = require("../../helpers/currency");

// ---------------------------------------------------------------------------
// Reference implementation — a literal copy of the inline logic from script.js
// so we can run expected vs actual without hand-computing every case.
// ---------------------------------------------------------------------------
function referenceFormatCurrency(amount, isOutflow = false, currency = "USD") {
  const currencySymbols = { USD: "$", PHP: "₱", EUR: "€", JPY: "¥" };
  if (isNaN(amount)) return "";
  const symbol = currencySymbols[currency] || "$";
  const formatter = new Intl.NumberFormat("en", {
    minimumFractionDigits: 2,
    maximumFractionDigits: 2,
  });
  const formattedAmount = formatter.format(Math.abs(amount));
  if (isOutflow) return `-${symbol}${formattedAmount}`;
  return `${symbol}${formattedAmount}`;
}

// ---------------------------------------------------------------------------
// Test matrix
// ---------------------------------------------------------------------------
// [description, amount, isOutflow, currency, expected]
//
// Expected values are generated by calling referenceFormatCurrency so that
// this file stays in sync automatically if Node's Intl behaviour changes.
// The only "manual" assertion is the structure of the output string.
// ---------------------------------------------------------------------------

const CURRENCIES = ["USD", "PHP", "EUR", "JPY"];
const AMOUNTS    = [0, 1, 100, 1234.5, 99999.99, 0.01, -50]; // negatives are displayed via isOutflow
const OUTFLOWS   = [false, true];

// Build the cross-product
const testMatrix = [];
for (const currency of CURRENCIES) {
  for (const amount of AMOUNTS) {
    for (const isOutflow of OUTFLOWS) {
      testMatrix.push([
        `${currency} | amount=${amount} | isOutflow=${isOutflow}`,
        amount,
        isOutflow,
        currency,
        referenceFormatCurrency(amount, isOutflow, currency),
      ]);
    }
  }
}

// Additional edge cases from the inline copies
const edgeCases = [
  // NaN → empty string (line 211 of script.js: if (isNaN(amount)) return "")
  ["NaN returns empty string",              NaN,       false, "USD", ""],
  ["NaN with isOutflow also returns empty", NaN,       true,  "PHP", ""],
  // Unknown currency falls back to "$"
  ["Unknown currency uses $ fallback",      100,       false, "XYZ", "$100.00"],
  ["Undefined currency uses $ fallback",    50,        false, undefined, "$50.00"],
  // Zero
  ["Zero, not outflow",                     0,         false, "USD", "$0.00"],
  ["Zero, outflow",                         0,         true,  "USD", "-$0.00"],
  // Negative amount: Math.abs() means the sign comes from isOutflow only
  ["Negative amount, isOutflow=false",      -100,      false, "USD", "$100.00"],
  ["Negative amount, isOutflow=true",       -100,      true,  "USD", "-$100.00"],
  // Specific known values from the script
  ["PHP 1000, outflow",                     1000,      true,  "PHP", "-₱1,000.00"],
  ["EUR 49.99, not outflow",                49.99,     false, "EUR", "€49.99"],
  ["JPY 1234.5, not outflow",               1234.5,    false, "JPY", "¥1,234.50"],
];

// ---------------------------------------------------------------------------
// Tests
// ---------------------------------------------------------------------------

describe("formatCurrency — byte-for-byte parity with all 5 inline copies", () => {
  describe("Full cross-product (currencies × amounts × outflow flags)", () => {
    test.each(testMatrix)("%s", (desc, amount, isOutflow, currency, expected) => {
      expect(formatCurrency(amount, isOutflow, currency)).toBe(expected);
    });
  });

  describe("Edge cases", () => {
    test.each(edgeCases)("%s", (desc, amount, isOutflow, currency, expected) => {
      expect(formatCurrency(amount, isOutflow, currency)).toBe(expected);
    });
  });
});

// ---------------------------------------------------------------------------
// CURRENCY_SYMBOLS constant
// ---------------------------------------------------------------------------
describe("CURRENCY_SYMBOLS", () => {
  test("contains exactly the four symbols from the inline copies", () => {
    expect(CURRENCY_SYMBOLS).toEqual({
      USD: "$",
      PHP: "₱",
      EUR: "€",
      JPY: "¥",
    });
  });
});

// ---------------------------------------------------------------------------
// formatCurrencyGlobal — reads window.userCurrency / global userCurrency
// ---------------------------------------------------------------------------
describe("formatCurrencyGlobal", () => {
  const originalUserCurrency = global.userCurrency;

  afterEach(() => {
    global.userCurrency = originalUserCurrency;
  });

  test("uses global userCurrency when set to PHP", () => {
    global.userCurrency = "PHP";
    expect(formatCurrencyGlobal(500, false)).toBe("₱500.00");
  });

  test("uses global userCurrency when set to EUR", () => {
    global.userCurrency = "EUR";
    expect(formatCurrencyGlobal(200, true)).toBe("-€200.00");
  });

  test("falls back to USD when global userCurrency is undefined", () => {
    global.userCurrency = undefined;
    expect(formatCurrencyGlobal(100, false)).toBe("$100.00");
  });

  test("falls back to $ when global userCurrency is an unknown code", () => {
    global.userCurrency = "ZZZ";
    expect(formatCurrencyGlobal(100, false)).toBe("$100.00");
  });

  test("NaN still returns empty string regardless of global currency", () => {
    global.userCurrency = "JPY";
    expect(formatCurrencyGlobal(NaN, false)).toBe("");
  });
});

// ---------------------------------------------------------------------------
// Verify the module's output matches the REFERENCE function on a large random
// sample — ensures no accidental divergence from script.js logic.
// ---------------------------------------------------------------------------
describe("Parity with reference implementation (100 random inputs)", () => {
  const seed = 42;
  function lcg(n) { return (n * 1664525 + 1013904223) & 0xffffffff; }

  let rng = seed;
  const randomTests = Array.from({ length: 100 }, (_, i) => {
    rng = lcg(rng);
    const amount   = ((rng & 0xffff) - 0x7fff) / 100; // -327.67 to +327.67
    rng = lcg(rng);
    const isOutflow = rng % 2 === 0;
    rng = lcg(rng);
    const currency  = CURRENCIES[rng % CURRENCIES.length];
    return [amount, isOutflow, currency];
  });

  test.each(randomTests.map((args, i) => [`random #${i}`, ...args]))(
    "%s",
    (_, amount, isOutflow, currency) => {
      expect(formatCurrency(amount, isOutflow, currency))
        .toBe(referenceFormatCurrency(amount, isOutflow, currency));
    }
  );
});
